//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaPhieuNhap { get; set; }
        public int MaNL { get; set; }
        public int SoLuongNhap { get; set; }
        public int Gia { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime HanSuDung { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
