//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public int MaPhieuXuat { get; set; }
        public int MaNL { get; set; }
        public int SoLuongXuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
